package main

import (
	"os"
	"text/template"
)

type Page struct {
	Title   string
	Content string
}

func main() {
	// シンプルなHTMLテンプレート
	tmplText := `
<html>
<head><title>{{.Title}}</title></head>
<body>
    <h1>{{.Title}}</h1>
    <p>{{.Content}}</p>
</body>
</html>
`
	tmpl, _ := template.New("page").Parse(tmplText)

	// データ
	p := Page{
		Title:   "My First SSG",
		Content: "This site was generated by Go!",
	}

	// 標準出力 (またはファイル) に書き出し
	tmpl.Execute(os.Stdout, p)
}
